[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
noCache = false

[deploy]
healthcheckPath = "/wp-login.php"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
